### PR TITLE
Update README with usage instructions

### PR DESCRIPTION
**Pull request by jieyouxu**
- Updated GUI screenshot.
- Also removed `building` section because it is no longer needed.

### CODE REVIEW

**Comment by trumank** [comment]
I've been using GitHub's image upload feature for embedding images in the readme. If you edit the file in the web view and drag and drop images into it, they'll be uploaded and will give you back a URL you can paste into  your local editor if you want. I think this is nicer than embedding a bunch of binary screenshots into the repo itself.

The app screenshots look great, though the mod.io screenshot is quite wide and hard to read.

**Comment by Buckminsterfullerene02** [comment]
In the "adding mod.io mods" section, it would be nice to also say that it's easy to obtain all the  links for your subscribed mods by either:
- using sandbox utilities copy mod list (or whatever that mod was that does it, I can't remember exactly)
- right clicking on the thumbnail of the mod on mod.io and hitting "copy link address" - which saves a bit of time not having to go into the mod and copying from the address bar. Seems obvious to us but remember how dumb end users can be... :)

Secondly, I think that you should mention that there are config files - that are stored in the locations described by the settings menu - and the parts or the whole of profile.json can be sent to other players if they so wish to send their mod profiles, at least until the proper solution is implemented further down the road.

**Comment by jieyouxu** [comment]
Changes:
- Use GitHub's image upload feature for the screenshots.
- Mention *A Better Modding Menu* for the copy mod list feature.
- Mention `profiles.json` sharing.

**Comment by trumank** [comment]
Oh, by too wide I meant the screenshot would look better if the original screenshot was taken with a smaller window size or zoomed in so there isn't as much dead space in the middle. The readme shrinks images already so no need to set a fixed size.

**Comment by jieyouxu** [comment]
Ah the fixed size was automatically added by upload, I'll remove it.

**Pull request merged**
