### PR TITLE
Add duplicate profile and rename profile functionality; rework profile selection and addition

### LINKED ISSUE #6: Add profile copy and paste

### PR DESCRIPTION
**Pull request by jieyouxu**
Screenshot 2023-08-02 145629

Closes #6.

### CODE REVIEW

**Comment by trumank** [comment]
The profile management UI is really clunky and needs a rework, but these features are indeed necessary.

Feeback:
- I don't think a status notification is necessary for immediate actions that cannot fail.
- Profile dropdown should be sorted so `profile` and `profile - Copy` appear next to each other
- When first opened, the rename dialog should be auto-filled with the current profile name and the text should be selected

...Actually I'm quite liking the modal dialog. The other profile actions (add, copy) could adopt it and the clunky combo/dropdown widget could just become a normal dropdown. Here's my proposal:
- Replace the profile widget with a non-editable combobox
- Make "add profile" open a modal dialog where the usage can enter a profile name
- Make "duplicate profile" open a modal dialog to enter a new name auto-filled with "<current profile> - Copy" or similar

**Comment by jieyouxu** [comment]
First batch of changes:
1. Removed status notifications for renaming the active profile.
2. Sorted the profile dropdown.
3. Prefill rename dialog with active profile name and auto-focus the textedit field.
4. Disable OK if profile name is empty or collides with existing profiles.

**Comment by jieyouxu** [comment]
Second batch of changes (GitHub PR seems to be not updating?):
1. Replaced profile selection with a non-editable combobox.
2. Made add profile open a modal dialog.
3. Made duplicate profile open a modal dialog with "`$ACTIVE_PROFILENAME` - Copy" prefilled.

**Comment by trumank** [comment]
😍

Last thing: Enter key doesn't submit the name modal. This can be added by checking `is_committed` on the response.

**Comment by jieyouxu** [comment]
Changes:
- Allowed enter key to submit the name modals.
- Fixed request focus logic to not repeatedly request focus every frame.

**Comment by trumank** [comment]
I de-duplicated the three similar popup functions and also also squashed a couple bugs:
- name textbox not being re-filled after previous popup was closed via esc or cancel
- profiles not always being saved after modification

How does that look?

**Comment by jieyouxu** [comment]
Looks good!

**Pull request merged**
